drop table if exists `task` CASCADE;
create table
	`task`
(
	id integer generated by default as identity,
	date_added varchar(255),
	date_completed varchar(255),
	task varchar(255),
	type varchar(255),
	primary key (id)

);